SELECT JOB_ID FROM EMPLOYEES;
SELECT DISTINCT JOB_ID FROM EMPLOYEES;

SELECT EMPLOYEE_ID, SALARY, CASE JOB_ID 
	WHEN 'AC_ACCOUNT' THEN SALARY + SALARY*0.1 
	WHEN 'AC_MGR' THEN SALARY + SALARY*0.2
	WHEN 'AD_VP' THEN SALARY + SALARY*0.5 
	ELSE SALARY 
	END AS "이번달 급여" 
	FROM EMPLOYEES;
	
SELECT EMPLOYEE_ID, 
		SALARY, 
		DECODE( JOB_ID, 'AC_ACCOUNT', SALARY + SALARY*0.1, 
						'AC_MGR',	SALARY + SALARY*0.2,
						'AD_VP',	SALARY + SALARY*0.5, 
									SALARY) AS "이번달 급여" 
	FROM EMPLOYEES;