-- date -> 문자열

select EMPLOYEE_ID, HIRE_DATE FROM EMPLOYEES;

select EMPLOYEE_ID, TO_CHAR( HIRE_DATE, 'YYYY-MM-DD HH:MI:SS' ) FROM EMPLOYEES;

select EMPLOYEE_ID, TO_CHAR( HIRE_DATE, 'YYYY"년" MM"월" DD"일" HH"시"MI"분"SS"초"' ) FROM EMPLOYEES;

--24시간제
select EMPLOYEE_ID, TO_CHAR( HIRE_DATE, 'YYYY"년" MM"월" DD"일" HH24"시"MI"분"SS"초" DAY D DDD"일째 되는날"' ) FROM EMPLOYEES;

select EMPLOYEE_ID, TO_CHAR( HIRE_DATE, 'YYYY"년" MM"월" DD"일" D"요일" DDD"일째 되는날"' ) FROM EMPLOYEES;

select EMPLOYEE_ID, TO_CHAR( HIRE_DATE, 'YEAR:SYEAR' ) FROM EMPLOYEES;

select EMPLOYEE_ID, TO_CHAR( HIRE_DATE, 'RR' ) FROM EMPLOYEES;
